---
- name: install prerequisites
  apt: name={{ item }} state=present
  with_items:
    - make
    - pbuilder
    - python-mock
    - python-configobj
    - python-support
    - python-psutil
    - cdbs
    - build-essential
  tags:
    - diamond

- name: checkout Diamond
  git: repo=https://github.com/python-diamond/Diamond.git dest=/root/Diamond accept_hostkey=yes force=yes
  tags:
    - diamond

- name: make builddeb
  shell: cd /root/Diamond && make builddeb creates=/root/Diamond/build/diamond_4.0.128_all.deb
  tags:
    - diamond

- name: install Diamond
  apt: deb=/root/Diamond/build/diamond_4.0.128_all.deb
  tags:
    - diamond

- name: put Diamond config
  template: src=diamond.conf dest=/etc/diamond/diamond.conf
  notify: restart diamond
  tags:
    - diamondconf
    - diamond
    - config

- name: start diamond service
  service: name=diamond state=started
  tags:
    - diamond

- name: enable diamond service
  service: name=diamond enabled=true
  tags:
    - diamond
