---
- name: install prerequisites
  apt: name={{ item }} state=present
  with_items:
    - make
    - pbuilder
    - python-mock
    - python-configobj
    - python-support
    - python-psutil
    - python-pip
    - cdbs
    - build-essential
  tags:
    - diamond
  when: ansible_os_family  == "Debian"

- name: install prerequisites
  yum: name={{ item }} state=present
  with_items:
    - make
    - python-mock
    - python-configobj
    - python-psutil
  tags:
    - diamond
  when: ansible_os_family  == "RedHat"

- name: checkout Diamond
  git: repo=https://github.com/python-diamond/Diamond.git dest=/root/Diamond accept_hostkey=yes force=yes
  tags:
    - diamond

- name: find out Dyamond version
  shell: ./version.sh chdir=/root/Diamond
  register: diamond_version
  changed_when: no

- name: make builddeb
  shell: cd /root/Diamond && make builddeb creates=/root/Diamond/build/diamond_{{ diamond_version.stdout }}_all.deb
  tags:
    - diamond
  when: ansible_os_family  == "Debian"

- name: make buildrpm
  shell: cd /root/Diamond && make buildrpm creates=/root/Diamond/dist/diamond-4.0.198-0.noarch.rpm
  tags:
    - diamond
  when: ansible_os_family  == "RedHat"

- name: install Diamond
  apt: deb=/root/Diamond/build/diamond_{{ diamond_version.stdout }}_all.deb
  tags:
    - diamond
  when: ansible_os_family  == "Debian"

- name: install Diamond
  yum: name=/root/Diamond/dist/diamond-4.0.198-0.noarch.rpm
  tags:
    - diamond
  when: ansible_os_family  == "RedHat"

- name: put Diamond config
  template: src=diamond.conf dest=/etc/diamond/diamond.conf
  notify: restart diamond
  tags:
    - diamondconf
    - diamond
    - config

- name: put cron.d file
  template: src=diamond dest=/etc/cron.d/diamond

- name: start diamond service
  service: name=diamond state=started
  tags:
    - diamond

- name: enable diamond service
  service: name=diamond enabled=true
  tags:
    - diamond
